# Generated by Django 4.1.1 on 2022-09-17 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='match_date',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_number',
            field=models.CharField(default='A1', max_length=16),
            preserve_default=False,
        ),
    ]
