# Generated by Django 4.1.1 on 2022-09-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='number',
            new_name='ticket_number',
        ),
        migrations.AddField(
            model_name='option',
            name='option_type',
            field=models.CharField(choices=[('ME', 'Meal'), ('SN', 'Snack'), ('DR', 'Drink'), ('SI', 'Side')], default='ME', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='info',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
